/* === DATABASE FARINE ESPANSO === */
/* Dati da Notion Database 🌾 Database Farine — allineato 15 marzo 2026 */

export interface FlourEntry {
  id: string;
  name: string;
  producer: string;
  category: "grano_tenero" | "manitoba" | "semola" | "integrale" | "gluten_free" | "speciale";
  w: number;
  w_std: number; // Standard deviation W (batch-to-batch variation, typically ±10-20)
  w_seasonal_variation_pct: number; // Seasonal ±% (spring harvest higher, autumn lower)
  pl: number;
  proteine_pct: number;
  assorbimento_pct: number;
  idratazione_ideale_pct: number;
  falling_number: number;
  stabilita_min: number;
  autolisi_necessaria: boolean;
  fermentazione_min_h: number;
  fermentazione_max_h: number;
  prezzo_eur_kg: number;
  stili_compatibili: string[];
  note: string;
}

/* === FARINE DATABASE (da Notion — 25 entries, allineate a marzo 2026) === */
export const FLOURS_DB: FlourEntry[] = [
  {
    id: "caputo_pizzeria",
    name: "Caputo Pizzeria (Blu)",
    producer: "Caputo",
    category: "grano_tenero",
    w: 265,
    w_std: 15,
    w_seasonal_variation_pct: 5,
    pl: 0.55,
    proteine_pct: 12.5,
    assorbimento_pct: 55,
    idratazione_ideale_pct: 60,
    falling_number: 300,
    stabilita_min: 7,
    autolisi_necessaria: false,
    fermentazione_min_h: 4,
    fermentazione_max_h: 24,
    prezzo_eur_kg: 1.0,
    stili_compatibili: ["napoletana_stg", "tonda_romana"],
    note: "Farina Tipo 00, il classico per pizza napoletana. Ottima per fermentazioni brevi e medie (4-24h).",
  },
  {
    id: "caputo_nuvola",
    name: "Caputo Nuvola",
    producer: "Caputo",
    category: "grano_tenero",
    w: 280,
    w_std: 15,
    w_seasonal_variation_pct: 5,
    pl: 0.55,
    proteine_pct: 12.5,
    assorbimento_pct: 61,
    idratazione_ideale_pct: 70,
    falling_number: 250,
    stabilita_min: 9,
    autolisi_necessaria: false,
    fermentazione_min_h: 8,
    fermentazione_max_h: 24,
    prezzo_eur_kg: 1.2,
    stili_compatibili: ["napoletana_stg", "napoletana_canotto", "teglia_romana", "pala_romana"],
    note: "Farina Tipo 0, ideale per cornicioni alveolati (canotto). Lievitazioni 18-24h.",
  },
  {
    id: "petra_5037",
    name: "Petra 5037",
    producer: "Petra (Molino Quaglia)",
    category: "grano_tenero",
    w: 320,
    w_std: 20,
    w_seasonal_variation_pct: 5,
    pl: 0.60,
    proteine_pct: 13.25,
    assorbimento_pct: 85,
    idratazione_ideale_pct: 80,
    falling_number: 280,
    stabilita_min: 15,
    autolisi_necessaria: true,
    fermentazione_min_h: 24,
    fermentazione_max_h: 72,
    prezzo_eur_kg: 1.8,
    stili_compatibili: ["napoletana_canotto", "teglia_romana", "pinsa_romana", "bonci_teglia", "pala_romana"],
    note: "Altissimo assorbimento (85%+). Ideale per lunghe maturazioni e alta idratazione. Teglia romana metodo Bonci.",
  },
  {
    id: "5stagioni_rossa",
    name: "5 Stagioni Napoletana Rossa",
    producer: "5 Stagioni",
    category: "grano_tenero",
    w: 300,
    w_std: 15,
    w_seasonal_variation_pct: 5,
    pl: 0.60,
    proteine_pct: 13.0,
    assorbimento_pct: 57,
    idratazione_ideale_pct: 65,
    falling_number: 300,
    stabilita_min: 13,
    autolisi_necessaria: false,
    fermentazione_min_h: 8,
    fermentazione_max_h: 48,
    prezzo_eur_kg: 1.3,
    stili_compatibili: ["napoletana_stg", "napoletana_canotto", "pala_romana", "grandma_style"],
    note: "Farina Tipo 00 per pizza napoletana. Ottima per lunghe maturazioni a freddo fino a 48h.",
  },
  {
    id: "dallagiovanna_manitoba_oro",
    name: "Dallagiovanna Manitoba Oro",
    producer: "Dallagiovanna",
    category: "manitoba",
    w: 390,
    w_std: 20,
    w_seasonal_variation_pct: 5,
    pl: 0.60,
    proteine_pct: 15.0,
    assorbimento_pct: 65,
    idratazione_ideale_pct: 70,
    falling_number: 350,
    stabilita_min: 20,
    autolisi_necessaria: true,
    fermentazione_min_h: 24,
    fermentazione_max_h: 96,
    prezzo_eur_kg: 2.0,
    stili_compatibili: ["napoletana_canotto", "pinsa_romana", "new_york"],
    note: "Farina Tipo 0 Manitoba forte. Elastica e tenace, ideale per lunghe lievitazioni (24-96h).",
  },
  {
    id: "manitoba_generica",
    name: "Manitoba Forte (Generica)",
    producer: "Generico",
    category: "manitoba",
    w: 380,
    w_std: 20,
    w_seasonal_variation_pct: 5,
    pl: 0.70,
    proteine_pct: 15.0,
    assorbimento_pct: 65,
    idratazione_ideale_pct: 70,
    falling_number: 400,
    stabilita_min: 18,
    autolisi_necessaria: true,
    fermentazione_min_h: 48,
    fermentazione_max_h: 120,
    prezzo_eur_kg: 2.5,
    stili_compatibili: ["napoletana_canotto", "new_york", "chicago_deep", "grandma_style"],
    note: "Farina di forza per lunghe lievitazioni e grandi idratazioni. Richiede autolisi.",
  },
  // Farine generiche (corrispondono ai FLOUR_W_RANGES del motore)
  {
    id: "00_generica",
    name: "Tipo 00 (Generica)",
    producer: "Generico",
    category: "grano_tenero",
    w: 195,
    w_std: 10,
    w_seasonal_variation_pct: 5,
    pl: 0.50,
    proteine_pct: 11.0,
    assorbimento_pct: 52,
    idratazione_ideale_pct: 58,
    falling_number: 320,
    stabilita_min: 5,
    autolisi_necessaria: false,
    fermentazione_min_h: 2,
    fermentazione_max_h: 12,
    prezzo_eur_kg: 0.8,
    stili_compatibili: ["tonda_romana", "focaccia_genovese", "sfincione"],
    note: "Farina debole, adatta a fermentazioni brevi e impasti senza pretese.",
  },
  {
    id: "0_generica",
    name: "Tipo 0 (Generica)",
    producer: "Generico",
    category: "grano_tenero",
    w: 240,
    w_std: 15,
    w_seasonal_variation_pct: 5,
    pl: 0.55,
    proteine_pct: 12.0,
    assorbimento_pct: 55,
    idratazione_ideale_pct: 62,
    falling_number: 300,
    stabilita_min: 7,
    autolisi_necessaria: false,
    fermentazione_min_h: 6,
    fermentazione_max_h: 24,
    prezzo_eur_kg: 1.0,
    stili_compatibili: ["napoletana_stg", "new_york", "padellino_torino", "grandma_style"],
    note: "Farina media, versatile per la maggior parte degli stili.",
  },
  {
    id: "integrale_generica",
    name: "Integrale Tipo 2",
    producer: "Generico",
    category: "integrale",
    w: 230,
    w_std: 15,
    w_seasonal_variation_pct: 5,
    pl: 0.55,
    proteine_pct: 13.5,
    assorbimento_pct: 70,
    idratazione_ideale_pct: 68,
    falling_number: 250,
    stabilita_min: 6,
    autolisi_necessaria: true,
    fermentazione_min_h: 8,
    fermentazione_max_h: 36,
    prezzo_eur_kg: 1.5,
    stili_compatibili: ["teglia_romana", "focaccia_genovese", "bonci_teglia"],
    note: "Ricca di fibre e nutrienti. Alveolatura rustica. Mix 30-50% con farina bianca consigliato.",
  },
  {
    id: "semola_generica",
    name: "Semola Rimacinata",
    producer: "Generico",
    category: "semola",
    w: 250,
    w_std: 15,
    w_seasonal_variation_pct: 5,
    pl: 0.65,
    proteine_pct: 12.5,
    assorbimento_pct: 55,
    idratazione_ideale_pct: 55,
    falling_number: 350,
    stabilita_min: 8,
    autolisi_necessaria: false,
    fermentazione_min_h: 4,
    fermentazione_max_h: 24,
    prezzo_eur_kg: 1.2,
    stili_compatibili: ["sfincione", "focaccia_genovese"],
    note: "Grano duro, colore giallo, sapore caratteristico. Mix 20-30% con grano tenero.",
  },
  // Farine di marca — da Notion Database 🌾 (espansione 15 marzo 2026)
  {
    id: "caputo_cuoco",
    name: "Caputo Cuoco (Saccorosso)",
    producer: "Caputo",
    category: "grano_tenero",
    w: 320,
    w_std: 20,
    w_seasonal_variation_pct: 5,
    pl: 0.60,
    proteine_pct: 13.0,
    assorbimento_pct: 57,
    idratazione_ideale_pct: 62,
    falling_number: 380,
    stabilita_min: 12,
    autolisi_necessaria: false,
    fermentazione_min_h: 24,
    fermentazione_max_h: 96,
    prezzo_eur_kg: 1.8,
    stili_compatibili: ["napoletana_stg", "tonda_romana", "napoletana_canotto"],
    note: "Farina professionale Tipo 00 per pizza napoletana classica. Lunghe maturazioni.",
  },
  {
    id: "petra_3_evolutiva",
    name: "Petra 3 Evolutiva",
    producer: "Petra (Molino Quaglia)",
    category: "grano_tenero",
    w: 340,
    w_std: 20,
    w_seasonal_variation_pct: 5,
    pl: 0.65,
    proteine_pct: 14.0,
    assorbimento_pct: 60,
    idratazione_ideale_pct: 65,
    falling_number: 390,
    stabilita_min: 15,
    autolisi_necessaria: true,
    fermentazione_min_h: 48,
    fermentazione_max_h: 120,
    prezzo_eur_kg: 2.8,
    stili_compatibili: ["napoletana_canotto", "tonda_romana", "pinsa_romana"],
    note: "Macinazione a pietra. Lunghe maturazioni 48-120h. Sapore complesso.",
  },
  {
    id: "5stagioni_5lune",
    name: "5 Stagioni Le 5 Lune",
    producer: "5 Stagioni",
    category: "grano_tenero",
    w: 350,
    w_std: 20,
    w_seasonal_variation_pct: 5,
    pl: 0.60,
    proteine_pct: 14.5,
    assorbimento_pct: 62,
    idratazione_ideale_pct: 67,
    falling_number: 400,
    stabilita_min: 16,
    autolisi_necessaria: true,
    fermentazione_min_h: 48,
    fermentazione_max_h: 96,
    prezzo_eur_kg: 2.5,
    stili_compatibili: ["napoletana_canotto", "new_york", "detroit"],
    note: "Farina di forza superiore per impasti complessi e lunghe lievitazioni.",
  },
  {
    id: "mix_gluten_free",
    name: "Mix Gluten-Free per Pizza",
    producer: "Generico",
    category: "gluten_free",
    w: 0,
    w_std: 0,
    w_seasonal_variation_pct: 0,
    pl: 0,
    proteine_pct: 9.0,
    assorbimento_pct: 80,
    idratazione_ideale_pct: 85,
    falling_number: 0,
    stabilita_min: 3,
    autolisi_necessaria: false,
    fermentazione_min_h: 1,
    fermentazione_max_h: 4,
    prezzo_eur_kg: 6.0,
    stili_compatibili: ["tonda_romana"],
    note: "Mix commerciale GF (riso+mais+tapioca+xantano). Lievitazione breve. Risultato simile a farina normale.",
  },
  // ═══ FARINE ALTERNATIVE — Espansione Fase B (16 marzo 2026) ═══
  {
    id: "farro_dicoccum",
    name: "Farro Dicocco (Emmer)",
    producer: "Generico",
    category: "speciale",
    w: 120,
    w_std: 10,
    w_seasonal_variation_pct: 5,
    pl: 0.45,
    proteine_pct: 13.0,
    assorbimento_pct: 65,
    idratazione_ideale_pct: 62,
    falling_number: 280,
    stabilita_min: 4,
    autolisi_necessaria: true,
    fermentazione_min_h: 4,
    fermentazione_max_h: 18,
    prezzo_eur_kg: 3.5,
    stili_compatibili: ["focaccia_genovese", "tonda_romana", "padellino_torino"],
    note: "Farro antico, sapore nocciolato. Glutine debole — mix 30-50% con grano tenero. Riduce FODMAP.",
  },
  {
    id: "farro_spelta",
    name: "Farina di Spelta (Farro Grande)",
    producer: "Generico",
    category: "speciale",
    w: 160,
    w_std: 10,
    w_seasonal_variation_pct: 5,
    pl: 0.50,
    proteine_pct: 14.5,
    assorbimento_pct: 60,
    idratazione_ideale_pct: 60,
    falling_number: 300,
    stabilita_min: 5,
    autolisi_necessaria: true,
    fermentazione_min_h: 6,
    fermentazione_max_h: 24,
    prezzo_eur_kg: 3.0,
    stili_compatibili: ["focaccia_genovese", "padellino_torino", "sfincione"],
    note: "Spelta: sapore dolce, glutine fragile. Mix 40-60% con 00 per struttura. Ottima per focacce rustiche.",
  },
  {
    id: "kamut_khorasan",
    name: "Kamut (Grano Khorasan)",
    producer: "Generico",
    category: "speciale",
    w: 180,
    w_std: 10,
    w_seasonal_variation_pct: 5,
    pl: 0.55,
    proteine_pct: 15.0,
    assorbimento_pct: 58,
    idratazione_ideale_pct: 58,
    falling_number: 350,
    stabilita_min: 6,
    autolisi_necessaria: true,
    fermentazione_min_h: 8,
    fermentazione_max_h: 24,
    prezzo_eur_kg: 4.5,
    stili_compatibili: ["tonda_romana", "focaccia_genovese"],
    note: "Grano antico ad alta proteina. Colore giallo dorato, sapore burroso. Mix 30-50% con grano tenero.",
  },
  {
    id: "segale",
    name: "Farina di Segale (Tipo 1)",
    producer: "Generico",
    category: "speciale",
    w: 80,
    w_std: 10,
    w_seasonal_variation_pct: 5,
    pl: 0.35,
    proteine_pct: 9.0,
    assorbimento_pct: 75,
    idratazione_ideale_pct: 70,
    falling_number: 200,
    stabilita_min: 3,
    autolisi_necessaria: false,
    fermentazione_min_h: 4,
    fermentazione_max_h: 12,
    prezzo_eur_kg: 2.5,
    stili_compatibili: ["focaccia_genovese", "sfincione"],
    note: "Pentosani rendono l'impasto appiccicoso. Max 15-20% nel mix. Sapore intenso, acido. Abbinamento ideale con lievito madre.",
  },
  {
    id: "riso",
    name: "Farina di Riso",
    producer: "Generico",
    category: "gluten_free",
    w: 0,
    w_std: 0,
    w_seasonal_variation_pct: 0,
    pl: 0,
    proteine_pct: 7.0,
    assorbimento_pct: 50,
    idratazione_ideale_pct: 75,
    falling_number: 0,
    stabilita_min: 2,
    autolisi_necessaria: false,
    fermentazione_min_h: 1,
    fermentazione_max_h: 4,
    prezzo_eur_kg: 2.0,
    stili_compatibili: ["tonda_romana"],
    note: "GF, neutra. Base per mix gluten-free (40-50%). Combinare con amidi (tapioca, mais) e idrocolloidi.",
  },
  {
    id: "mais",
    name: "Farina di Mais (Bramata Fine)",
    producer: "Generico",
    category: "gluten_free",
    w: 0,
    w_std: 0,
    w_seasonal_variation_pct: 0,
    pl: 0,
    proteine_pct: 8.5,
    assorbimento_pct: 55,
    idratazione_ideale_pct: 70,
    falling_number: 0,
    stabilita_min: 2,
    autolisi_necessaria: false,
    fermentazione_min_h: 1,
    fermentazione_max_h: 4,
    prezzo_eur_kg: 1.5,
    stili_compatibili: ["sfincione"],
    note: "GF, colore giallo. Croccantezza superficiale. Max 20-30% nel mix con grano tenero, o 40% in mix GF.",
  },
  {
    id: "grano_saraceno",
    name: "Farina di Grano Saraceno",
    producer: "Generico",
    category: "gluten_free",
    w: 0,
    w_std: 0,
    w_seasonal_variation_pct: 0,
    pl: 0,
    proteine_pct: 12.0,
    assorbimento_pct: 70,
    idratazione_ideale_pct: 65,
    falling_number: 0,
    stabilita_min: 2,
    autolisi_necessaria: false,
    fermentazione_min_h: 2,
    fermentazione_max_h: 8,
    prezzo_eur_kg: 4.0,
    stili_compatibili: ["focaccia_genovese"],
    note: "GF nonostante il nome. Sapore terroso-nocciolato intenso. Max 15-25% nel mix. Tipico della tradizione alpina.",
  },
  {
    id: "avena",
    name: "Farina d'Avena",
    producer: "Generico",
    category: "speciale",
    w: 90,
    w_std: 10,
    w_seasonal_variation_pct: 5,
    pl: 0.40,
    proteine_pct: 13.0,
    assorbimento_pct: 65,
    idratazione_ideale_pct: 65,
    falling_number: 250,
    stabilita_min: 3,
    autolisi_necessaria: false,
    fermentazione_min_h: 3,
    fermentazione_max_h: 12,
    prezzo_eur_kg: 2.5,
    stili_compatibili: ["focaccia_genovese", "padellino_torino"],
    note: "Beta-glucani la rendono morbida. Max 15-20% nel mix con grano tenero. Sapore dolce. GF certificata disponibile.",
  },
  {
    id: "teff",
    name: "Farina di Teff",
    producer: "Generico",
    category: "gluten_free",
    w: 0,
    w_std: 0,
    w_seasonal_variation_pct: 0,
    pl: 0,
    proteine_pct: 11.0,
    assorbimento_pct: 80,
    idratazione_ideale_pct: 75,
    falling_number: 0,
    stabilita_min: 2,
    autolisi_necessaria: false,
    fermentazione_min_h: 2,
    fermentazione_max_h: 8,
    prezzo_eur_kg: 6.0,
    stili_compatibili: [],
    note: "GF, grano etiope. Alto ferro e calcio. Sapore di malto-cioccolato. Max 20-30% nel mix GF. Costoso.",
  },
  {
    id: "ceci",
    name: "Farina di Ceci",
    producer: "Generico",
    category: "gluten_free",
    w: 0,
    w_std: 0,
    w_seasonal_variation_pct: 0,
    pl: 0,
    proteine_pct: 20.0,
    assorbimento_pct: 90,
    idratazione_ideale_pct: 80,
    falling_number: 0,
    stabilita_min: 2,
    autolisi_necessaria: false,
    fermentazione_min_h: 1,
    fermentazione_max_h: 4,
    prezzo_eur_kg: 3.0,
    stili_compatibili: ["focaccia_recco"],
    note: "GF, alta proteina. Tradizionale nella farinata/cecina ligure. Max 10-15% nel mix pizza per sapore e croccantezza.",
  },
  {
    id: "tipo1_macinata_pietra",
    name: "Tipo 1 Macinata a Pietra",
    producer: "Generico",
    category: "grano_tenero",
    w: 220,
    w_std: 15,
    w_seasonal_variation_pct: 5,
    pl: 0.55,
    proteine_pct: 12.5,
    assorbimento_pct: 58,
    idratazione_ideale_pct: 63,
    falling_number: 280,
    stabilita_min: 7,
    autolisi_necessaria: false,
    fermentazione_min_h: 8,
    fermentazione_max_h: 36,
    prezzo_eur_kg: 1.8,
    stili_compatibili: ["napoletana_stg", "focaccia_genovese", "padellino_torino", "sfincione"],
    note: "Semi-integrale rustica. Sapore complesso, fibre parziali. Ottimo compromesso tra 00 e integrale.",
  },
];

/* === HELPERS === */

/** Trova farine compatibili con uno stile */
export function getCompatibleFlours(styleId: string): FlourEntry[] {
  return FLOURS_DB.filter((f) => f.stili_compatibili.includes(styleId));
}


/** Etichetta categoria farina */
export const FLOUR_CATEGORY_LABELS: Record<string, { label: string; emoji: string }> = {
  grano_tenero: { label: "Grano tenero", emoji: "🌾" },
  manitoba: { label: "Manitoba", emoji: "💪" },
  semola: { label: "Semola", emoji: "🌻" },
  integrale: { label: "Integrale", emoji: "🟤" },
  gluten_free: { label: "Gluten-Free", emoji: "🚫" },
  speciale: { label: "Speciale", emoji: "✨" },
};

/** Suggerisci farine per una ricetta (by style + W + fermentation hours) */
export function suggestFlours(
  styleId: string,
  recipeW: number,
  fermentationHours: number,
  maxResults: number = 3,
): FlourEntry[] {
  // Priority: style-compatible first, then W-compatible, sorted by distance
  const scored = FLOURS_DB
    .filter((f) => f.w > 0) // exclude GF/non-W flours
    .map((f) => {
      let score = 0;
      // Style match bonus
      if (f.stili_compatibili.includes(styleId)) score += 50;
      // W distance penalty (closer = better)
      const wDist = Math.abs(f.w - recipeW);
      score -= wDist * 0.1;
      // Fermentation time compatibility bonus
      if (fermentationHours >= f.fermentazione_min_h && fermentationHours <= f.fermentazione_max_h) {
        score += 25;
      }
      // Brand bonus (non-generic preferred for suggestions)
      if (f.producer !== "Generico") score += 10;
      return { flour: f, score };
    })
    .sort((a, b) => b.score - a.score)
    .slice(0, maxResults)
    .map((s) => s.flour);
  return scored;
}

/**
 * Calcola il range W effettivo considerando variabilita batch-to-batch e stagionale.
 * Audit DB Engineer: "W=260-280 variabile, ±10% batch, ±5% stagione"
 * Restituisce [wMin, wMax] a 1 deviazione standard + variazione stagionale.
 */
export function getEffectiveWRange(flour: FlourEntry): [number, number] {
  if (flour.w === 0) return [0, 0]; // GF flours
  const seasonalDelta = flour.w * (flour.w_seasonal_variation_pct / 100);
  const totalVariation = flour.w_std + seasonalDelta;
  return [
    Math.round(flour.w - totalVariation),
    Math.round(flour.w + totalVariation),
  ];
}